Update examples
terra-farm/terraform-provider-xenorchestra pull request #70
Opened 2020-09-30 21:32 UTC by brd

2020-10-01 01:44 UTC, ddelnano requested changes
Thanks for making these changes! I noticed these but put the fix in a long PR do I'm glad it's getting fixed sooner.

One minor comment otherwise looks good

2020-10-01 01:44 UTC, ddelnano commented on docs/resources/vm.md
> +	  network_id = data.xenorchestra_pif.pif.network
Can you switch this to a `data.xenorchestra_network` data source since that is more appropriate?

2020-10-07 04:35 UTC, ddelnano commented
@brd I went ahead and merged your change + my suggestion in #73.

2020-10-07 04:35 UTC, closed without merging

2020-10-07 14:03 UTC, brd commented
Thanks, sorry I kept getting distracted.